### ISSUE TITLE
bilstm외에는 에러가납니다.

### ISSUE THREAD

**Issue by ssifood** [Taekyoon/takos-alpha#1]
spacing_cnn_bilstm_configs.json 이 파일을 제가 가진 트레이닝 데이터셋 수정해서 돌리면, 토크나이져가 설정되지 않아서 에러나고, 토크나이져를 syllable_tokenizer 로 설정하면  인덱스에러가 납니다.

Q. spacing_bilstm_configs.json (bilstm용) 이것말고  bert나 cnn_bilstm등 다를 모델 사용할수 있는
config파일이나, 셋팅법이 궁금합니다.

**Comment by Taekyoon** [comment]
늦게 답변을 드려서 죄송합니다.
아직 프로젝트를 하고 계신다면, 혹시 구체적인 로그를 한번만 올려주실 수 있을까요?

**Comment by ssifood** [comment]
안녕하세요.
 
답장주셔서 감사합니다. takos개발자님.
제가 한글 띄어쓰기에 관심이 있어서요. 하하하하하 (프로젝트상..)
 
우선 bert_configs.json을 만들어서  진행하면 에러가납니다.
실행은 우선, test_word_segmentation.py롤 간단히 바꿔서 진행하였습니다.
 
그래도 에러가나서 이렇게 질문드립니다. 
 
첨부파일 : test_word_segmentation.png  (에러내용)
          test_word_segmentation_source.png (실행소스내용)
          berf_cofigs.png  (bert_configs.json 파일내용)
 
바쁜신데  시간과 열정을 주셔서 정말 감사합니다.
 
 
 
-----Original Message-----

**Comment by Taekyoon** [comment]
첨부파일이 보이질 않아서 혹시 제 메일로 컨텍을 주시면 감사할 것 같습니다.
tgchoi03@gmail.com 입니다.
