### ISSUE TITLE
takos-alpha 이슈 정리

### ISSUE THREAD

**Issue by Foreist** [Taekyoon/takos-alpha#2]
안녕하세요. takos-alpha를 실행하는 과정에서 발생한 에러들을 적어보고자 합니다.

git clone https://github.com/Taekyoon/takos-alpha.git
pip install -r requirements
python setup.py install

두 번째 부분에서 ! pip install -r requirements.txt로 바꿔주시고, 세 번째 줄로 설치를 하고 실행시 인코딩 에러가 발생할 경우에는 
pip install -r requirements
python setup.py install
이 부분을 takos-alpha폴더에서 실행해주시면 됩니다.
경로를 바꾸는 경우에 프로그램 실행시 인코딩 에러가 발생합니다.

일단 scripts의 json 파일들을 실행시키면 될 것 같아서 그렇게 진행해봤는데요.
![image](https://user-images.githubusercontent.com/46616734/74900532-7abb5380-53e3-11ea-8e40-24a1a15f3549.png)

위 파일과 아래 파일의 에러가 다릅니다.
![image](https://user-images.githubusercontent.com/46616734/74900557-932b6e00-53e3-11ea-9163-36418ed73585.png)

test/scripts에 있는 파일을 실행시키면 첫 번째 사진과 같이 no best model이라는 메시지가 생성됩니다.

제가 해당 프로젝트로 하고자 하는 것은 biLSTM+CRF 모델을 학습시키고 싶은데 해당 프로젝트의 사용법을 잘 모르겠습니다.

**Comment by Taekyoon** [comment]
@Foreist 네 안녕하세요. 
말씀하신 이슈를 살펴보았는데요.

첫 번째 이슈 'no best model'이라 뜨는 문제는 학습한 모델이 현재 없다는 이야기 입니다.
데이터를 가지고 `WordSegmentAgent.train()` 함수를 활용하셔서 학습을 진행하시면 됩니다.
데이터를 가지고 있지 않으시다면 세종 데이터셋을 활용하시면 됩니다.
아래 링크를 참고하시면 좋을 듯 하고요.
링크: https://www.slideshare.net/TaekyoonChoi/taekyoon-choi-pycon

두 번째 이슈는 토크나이저 설정이 되어있지 않아서 발생한 문제입니다.
`config.json` 파일에 `"tokenizer": "syllable_tokenizer"`를 추가하시면 아마 문제가 해결 되실 듯 합니다.
이 부분은 수정해보시고 제대로 동작이 된다면 Pull Request 보내주시면 정말 감사할 것 같습니다 ㅎㅎ

관심있게 봐주셔서 감사하고 좋은 프로젝트 잘 진행되셨으면 좋겠습니다.

이 이슈는 문제가 해결 되실때까지 열어두도록 하겠습니다.

**Comment by Foreist** [comment]
두 번째 이슈는 

```
{
  "type": "word_segment",
  "gpu_device": -1,
  "load_model": null,
  "tokenizer": "syllable_tokenizer",
  "dataset": {
    "name": "your_dataset",
    "train": {
      "vocab_min_freq": 10,
      "input": "./samples/train.txt"
    },
    "test": {
      "limit_len": 150,
      "input": "./samples/test.txt"
    }
  },
  "deploy": {
    "path": "./tmp/cnn_bilstm_spacing"
  },
  "model": {
    "type": "cnn_bilstm_crf",
    "parameters": {
      "word_embedding_dims": 32,
      "channel_dims": 32,
      "conv_configs": [
        {
          "channel_size": 32,
          "kernel_size": 3,
          "padding": 1
        },
        {
          "channel_size": 32,
          "kernel_size": 5,
          "padding": 2
        },
        {
          "channel_size": 32,
          "kernel_size": 7,
          "padding": 3
        }
      ],
      "hidden_dims": 64
    }
  },
  "train": {
     "epochs": 100,
    "eval_steps": -1,
    "learning_rate": 3e-4,
    "eval_batch_size": 10,
    "batch_size": 64,
    "sequence_length": 50
  }
}
```

이런 식으로 추가하면 위와 같이 no best model이라고 뜨더라고요.
세종 데이터셋으로 corpus 만들 때는 처음 make만 make all로 해주면 데이터 생성에는 문제가 없는 것 같습니다.
그런데 WordSegmentAgent('./corpus.txt').train()에서 
![image](https://user-images.githubusercontent.com/46616734/75129214-44dfdd00-570b-11ea-842d-6f81dfd24ab8.png)
이런 식의 에러가 나는데, 아무래도 원하는 json 형식으로 키값을 추가한다거나 하는 식으로 바꿔줘야 할 것 같은데, 세종 corpus에서 바로 text만 추출한 txt로는 뭔가 되지가 않네요 ㅠㅠ
이 부분은 어떻게 해결하면 좋을까요?

**Comment by Taekyoon** [comment]
@Foreist 
위에 에러는 json 파일을 읽다가 발생한 에러로 보입니다.
먼저 json 양식이 validate 한지 먼저 확인해보시고 다시 실행해보시면 될 겁니다.

이후에 다른 문제가 발생하면 업데이트 주세요!

**Comment by Foreist** [comment]
안녕하세요. 이번에는 
WordSegmentAgent('./scripts/spacing_bilstm_configs.json').train()와 같은 방법을 통해서 학습을 어떻게 시켜야 하는지까지는 이해를 했는데요.
```

{
  "type": "word_segment",
  "gpu_device": 0,
  "load_model": null,
  "tokenizer": "syllable_tokenizer",
  "dataset": {
    "name": "your_dataset",
    "train": {
      "vocab_min_freq": 10,
      "input": "./trainer.txt"
    },
    "test": {
      "limit_len": 150,
      "input": "./tester.txt"
    }
  },
  "deploy": {
    "path": "./tmp/bilstm_spacing"
  },
  "model": {
    "type": "bilstm_crf",
    "parameters": {
      "word_embedding_dims": 32,
      "hidden_dims": 64
    }
  },
  "train": {
    "epochs": 100,
    "eval_steps": -1,
    "learning_rate": 3e-4,
    "eval_batch_size": 10,
    "batch_size": 64,
    "sequence_length": 50
  }
}

```
위 코드가 ```spacing_bilstm_configs.json```파일입니다.
train input과 test input은 태균 님이 발표 때 진행하신 것처럼 세종코퍼스 데이터셋을 9:1비율로 랜덤하게 나눠서 진행하였는데요.
학습 속도가 말도 안 되게 빠르길래 train input 쪽을 '.' 이런 식으로 바꾸어도 학습이 되더라고요.
혹시 기본 train input값이 지정이 되어 있다거나 하는 것이 있는데 제가 모르고 있다면 조언을 구하고 싶습니다.

**Comment by Foreist** [comment]
학습 부분은 제가 양식 자체를 잘못 이해하고 있는 것 같아서 고쳐보았더니 진행은 되는데 학습을 시키고자 하는 데이터를 바꿔도 학습하는 속도가 똑같아서요.
해당 부분 다시 이슈에 올렸습니다.
더불어서 저도 공부를 해서 선생님처럼 문제 해결을 위한 모델을 만들고 싶은데 기초적인 부분이 부족해서 그런지 선생님의 코드조차 이해하기 쉽지 않네요.
이미지 쪽은 이미 양식이 다 정해져 있어서 배울 때나 응용 시에도 NLP 쪽으로 공부를 진행하다 보니 이론은 이해를 하더라도 구현 쪽에서 쉽지가 않네요.
그래서 지금은 파이토치를 기초부터 공부해서 RNN과 LSTM을 문서참고 없이 구현할 수 있을 때까지 공부하려고 하는데 혹시 선생님은 자연어처리 쪽을 어떤 식으로 공부하셨는지 여쭙고자 합니다.

**Comment by Taekyoon** [comment]
@Foreist 
정확한 파일 경로를 지정하지 않으면 학습이 안될 것으로 봅니다. 혹시 진행하신 로그를 남겨주시면 제가 파악을 더 잘 해볼 수 있을 것 같습니다.
혹시 로그를 남겨주실 수 있을까요?

**Comment by Foreist** [comment]
config file: https://tmpstorage.com/download/nkcru3nteu
train_log file: https://tmpstorage.com/download/vevca0yauz
입니다.
config 쪽 train, test 경로에 있는 파일은 제가 학습시키고자 하는 파일입니다.
경로를 "." 이런 식으로 지우든 다른 파일로 대체를 하든 항상 학습이 되고 속도가 똑같은 것 같습니다
